schema_version = "1.0.0"

id = "perspective_plotter"
version = "1.2.4"
name = "Perspective Plotter"
tagline = "Match a camera according to perspective lines"
maintainer = "Mark Kingsnorth <info@configurate.net>"
type = "add-on"

website = "https://perspective-plotter.readthedocs.io/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["3D View"]

blender_version_min = "3.0.0"
license = [
  "SPDX:GPL-2.0-or-later",
]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl"
# ]

# Optional: build setting.
# https://docs.blender.org/manual/en/dev/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
paths_exclude_pattern = [
  "/.git/",
 "__pycache__/"
]