name = "Place Helper"
id = "PlaceHelper"
maintainer = "AIGODLIKE社区,Atticus,小萌新"
tagline = "Easily place objects in Blender"
type = "add-on"
schema_version = "1.0.0"
blender_version_min = "4.2.0"
version = "1.3.8"
tags = ["3D View", "Modeling", "Object"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/AIGODLIKE/PlaceHelper"
