schema_version = "1.0.0"

id = "procedural_chain"
version = "4.2.0"
name = "Procedural Chain"
tagline = "Procedural Chain"
maintainer = "Pedro Henrique"
type = "add-on"
blender_version_min = "4.2.3"
license = ["SPDX:MIT"]
